import Button from "@/components/Button";
import Layout from "@/components/Layout";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<br />
				<Link href="/images">
					<Button className="w-72 bg-gradient-to-r from-indigo-600 to-blue-500 hover:from-blue-500 hover:to-indigo-600 active:from-indigo-800 active:to-red-500 text-white font-bold py-3 px-4 rounded-full transition duration-300 ease-in-out focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-opacity-50">
						Enter Site
					</Button>
				</Link>
			</Layout>
		</>
	);
}
